
// Action types
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const INCREMENT_IF_ODD = 'INCREMENT_IF_ODD'

export const INCREMENT_ASYNC = 'INCREMENT_ASYNC'
export const CANCEL_INCREMENT_ASYNC = 'CANCEL_INCREMENT_ASYNC'

export const RECEIVE_API_DATA = 'RECEIVE_API_DATA'
export const GET_ALL_TWITTER_TWEET = 'GET_ALL_TWITTER_TWEET'
export const COUNTDOWN_TERMINATED = 'COUNTDOWN_TERMINATED'

